name: Main Workflow
on:
  push:
    branches: [ master ]
jobs:
  main_workflow:
    name: Main Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: check_and_create_directories
        name: Check and Create Directories
        run: |
          if ! [[ -d "docs/json" ]]; then
            mkdir -p docs/json
          fi

      - id: check_and_create_main_start_md5
        name: Check and Create Main Start MD5
        if: steps.check_and_create_directories.conclusion == 'success'
        run: |
          workflow_init_template='{\n\t"schemaVersion": 1,\n\t"color": "00aedb",\n\t"label": "PLACEHOLDER",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "linux"\n}'
          if ! [[ -f "docs/json/workflow_init_md5.json" ]]; then
            touch docs/json/workflow_init_md5.json
          fi
          echo -e "$workflow_init_template" > docs/json/workflow_init_md5.json
          sed -i "s/\"label\": \".*\"/\"label\": \"Workflow Start\"/g" docs/json/workflow_init_md5.json
          sed -i "s/\"message\": \".*\"/\"message\": \"$(date)\"/g" docs/json/workflow_init_md5.json
      - id: check_and_create_main_stop_md5
        name: Check and Create Main Stop MD5
        if: steps.check_and_create_main_start_md5.conclusion == 'success'
        run: |
          workflow_init_template='{\n\t"schemaVersion": 1,\n\t"color": "00aedb",\n\t"label": "PLACEHOLDER",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "linux"\n}'
          if ! [[ -f "docs/json/workflow_stop_md5.json" ]]; then
            touch docs/json/workflow_stop_md5.json
          fi
          echo -e "$workflow_init_template" > docs/json/workflow_stop_md5.json
          sed -i "s/\"label\": \".*\"/\"label\": \"Workflow Stop\"/g" docs/json/workflow_stop_md5.json
          sed -i "s/\"message\": \".*\"/\"message\": \"$(date)\"/g" docs/json/workflow_stop_md5.json
      - id: check_and_commit
        name: Commit Changes
        if: steps.check_and_create_main_stop_md5.conclusion == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Completed Main Workflow